apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.frontend.name }}
spec:
  replicas: {{ .Values.deployment.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.frontend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.frontend.labels.app }}
        date: "{{ .Release.Time.Seconds }}"
    spec:
      containers:
        - name: {{ .Values.deployment.frontend.container.name }}
          image: {{ .Values.deployment.frontend.container.image }}
          ports:
            - containerPort: {{ .Values.deployment.frontend.container.port }}
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.backend.name }}
spec:
  replicas: {{ .Values.deployment.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.backend.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.backend.labels.app }}
        date: "{{ .Release.Time.Seconds }}"
    spec:
      containers:
        - name: {{ .Values.deployment.backend.container.name }}
          image: {{ .Values.deployment.backend.container.image }}
          ports:
            - containerPort: {{ .Values.deployment.backend.container.port }}
          imagePullPolicy: Always